# Generated by Django 4.2.7 on 2023-11-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='house',
            name='map_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='photos',
            field=models.ImageField(default='default.jpg', upload_to='house_photos/'),
        ),
    ]
