# Generated by Django 4.2.7 on 2023-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_description_house_map_location_house_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
