# Generated by Django 4.2.7 on 2023-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_land_description_land_map_location_land_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
